# Generated by Django 4.0.6 on 2023-01-11 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentOptionmethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicKey', models.CharField(max_length=50)),
                ('privateKey', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('userNme', models.CharField(max_length=50)),
                ('passwordkey', models.CharField(max_length=50)),
                ('amount', models.PositiveIntegerField()),
                ('payIcon', models.ImageField(upload_to='paymenImag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='clientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uudiUser', models.CharField(blank=True, max_length=50)),
                ('referLink', models.URLField(max_length=500)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='method', to='client.paymentoptionmethods')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clentdeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transittionuudi', models.CharField(blank=True, max_length=50)),
                ('dataDepsited', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('withdrawalable', models.PositiveIntegerField()),
                ('paymentOption', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.paymentoptionmethods')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
