# Generated by Django 4.0.6 on 2023-01-11 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clentdeposit',
            name='paymentOption',
        ),
        migrations.AlterField(
            model_name='clentdeposit',
            name='dataDepsited',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='clentdeposit',
            name='update',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='clentdeposit',
            name='withdrawalable',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='method', to='client.paymentoptionmethods'),
        ),
        migrations.AlterField(
            model_name='paymentoptionmethods',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentoptionmethods',
            name='passwordkey',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentoptionmethods',
            name='payIcon',
            field=models.ImageField(blank=True, null=True, upload_to='paymenImag'),
        ),
        migrations.AlterField(
            model_name='paymentoptionmethods',
            name='privateKey',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentoptionmethods',
            name='publicKey',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentoptionmethods',
            name='userNme',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
