# Generated by Django 4.0.6 on 2023-01-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_clentdeposit_paymentoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='referLink',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
