# Generated by Django 4.0.6 on 2023-01-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_clientuser_referlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='uudiUser',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
